// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChQ_wjZ6HfhTwn6OCWxAu4IACIKS8aZgY',
    appId: '1:926534037297:web:f88d9fa53e25618f0d0a10',
    messagingSenderId: '926534037297',
    projectId: 'anasoil',
    authDomain: 'anasoil.firebaseapp.com',
    storageBucket: 'anasoil.firebasestorage.app',
    measurementId: 'G-ZQR7DGQDQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvo-gR4hEOFnh1xdDvpMN8Yzvq_jgzpXo',
    appId: '1:926534037297:android:38d4d08dddbfb1c60d0a10',
    messagingSenderId: '926534037297',
    projectId: 'anasoil',
    storageBucket: 'anasoil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnmgSArCtsefiXjB3NDJ8loXf1f1QLeOA',
    appId: '1:926534037297:ios:9d0aa363435b5ff90d0a10',
    messagingSenderId: '926534037297',
    projectId: 'anasoil',
    storageBucket: 'anasoil.firebasestorage.app',
    iosBundleId: 'com.example.anasoilAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnmgSArCtsefiXjB3NDJ8loXf1f1QLeOA',
    appId: '1:926534037297:ios:9d0aa363435b5ff90d0a10',
    messagingSenderId: '926534037297',
    projectId: 'anasoil',
    storageBucket: 'anasoil.firebasestorage.app',
    iosBundleId: 'com.example.anasoilAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChQ_wjZ6HfhTwn6OCWxAu4IACIKS8aZgY',
    appId: '1:926534037297:web:4ce84cb1785a3f3c0d0a10',
    messagingSenderId: '926534037297',
    projectId: 'anasoil',
    authDomain: 'anasoil.firebaseapp.com',
    storageBucket: 'anasoil.firebasestorage.app',
    measurementId: 'G-3V8GS4RWJ2',
  );
}
